{
  "hash": "6d74565e4ac924257ac5a30d62a63a82",
  "result": {
    "engine": "knitr",
    "markdown": "# External data and data import\n\nData files come in various formats, and understanding these formats is crucial for efficient\ndata import into R. While R can handle a multitude of data types, some are far more prevalent in the scientific community. Scientists frequently work with structured data, where observations (rows) and variables (columns) are clearly defined, and this is what we\nwill discuss here. This chapter will introduce you to the most common formats you will encounter, briefly explain their structure, why they are widely used and finally how to import them in R.\n\n```         \nneed to mention the woo paper about data structure..\n```\n\n## Understanding common data formats\n\nWe start our discussion by examining common data formats encountered. Unconventionally, we will start with Excel workbooks\n\n### Microsoft Excel Workbooks (.xlsx)\n\nExcel workbooks are a pervasive format, particularly in laboratories and smaller research groups, due to their user-friendly interface and powerful built-in functionalities. Excel files contain multiple worksheets, each containing cells of data that are typically organized as a grid of rows and columns.\n\nWhen we discuss the benefits of Excel for storing data and use in R, we only want to focus on it's user-friendly interface for manual data entry and organisation, and it's ability to organise related data in different worksheets of the same file.\n\nIt's ability to provide free-form data structure (not necessarily in a grid of rows and columns) and cell formatting options may seem useful for data analysis *in Excel*, but this often creates messy data with inconsistencies, merged cells, random notes, and other non-standard formatting that make programmatic import into R challenging. \n\nOur suggestion for keeping raw data in Excel files is to ensure that 1) raw data is kept in a consistent tabular structure with rows and columns, 2) no additional/subsequent analytical information e.g. means of groups/rows or cell formatting is included and 3) each individual dataset is kept in a separate spreadsheet. \n\n\n#### Advantages {.unnumbered}\n\n- User-friendly interface: easy manual data entry and organization.\n\n- Multiple worksheets: allows for organizing related data into different tabs within a single file.\n\n- Formatting options: Enables visual organization and presentation of data.\n\n#### Disadvantages {.unnumbered}\n\n-   Potential for \"messy data\": the flexibility of Excel can lead to poorly structured data, inconsistencies, merged cells, or Excel specific formatting that can make import into R challenging.\n\n-   Proprietary format: requires additional R packages and can sometimes be slower or more resource-intensive than reading plain text files.\n\n- Scalability issues: for very large datasets, Excel can become slow and unwieldy.\n\n\n### Text Delimited Files (.csv, .tsv, .txt)\n\nText delimited files such as Comma-Separated Values (CSV) and Tab-Separated Values (TSV) are arguably the most common and versatile plain-text format for tabular data, and their simplicity is their strength. These are simply text files where data values are separated by a **delimiter** such as a comma `,` tab ` `, pipe `|` or other character, and each row represents a new line of data. \n\nIf you were to open a `.csv` or `.tsv` file in a text editor, you would see something like the following\n\n#### CSV {.unnumbered}\n\n```r         \nSampleID,Treatment,Replicate,Measurement1,Measurement2\nA1,Control,1,12.5,3.2\nA2,Treated,1,15.1,4.5\nB1,Control,2,11.9,3.0\n```\n\n#### TSV {.unnumbered}\n\n```r        \nSampleID    Treatment   Replicate   Measurement1    Measurement2\nA1  Control 1   12.5    3.2\nA2  Treated 1   15.1    4.5\nB1  Control 2   11.9    3.0\n```\n\n#### Advantages {.unnumbered}\n\n- Universally supported: nearly all spreadsheet software, programming languages, and databases can read and write text files.\n\n- Human-readable: you can open and inspect a file with any basic text editor, making it easy to spot errors or understand its structure.\n\n- Lightweight: Text files are typically small in size compared to more complex formats like Excel. However, very large files can be common.\n\n#### Disadvantages {.unnumbered}\n\n- No Formatting: text files store only data, not formatting like data type, or software specific formats (fonts, colors, cell styles).\n\n### R's own data files\n\nR has it's own native data files commonly ending in `.rds`, `.RData` or `.rda`. These are binary files specifically designed to store one or more R objects. This format is highly efficient for saving and loading data within the R environment, preserving data types and structures precisely. They are excellent for internal R workflows due to their efficiency and perfect preservation of R objects, however, given they are proprietary to R, they cannot be directly opened or read by other software applications.\n\n### Other data types and sources\n\nDespite the popularity of Excel and text data files, it is quite possible that you may need to handle data originating from other sources. You may need to extract data from specialized instruments or sensors that produce data in unique binary or other proprietary formats. However, these tend to have software that allow you to further export the data in a tabular structure in a text data file. Data may also be shared to you from specialized statistical software packages like SAS, SPSS, or Stata, each with its own proprietary file format. R boasts a rich ecosystem of packages for importing virtually any data type and it should be straightforward to import these\ndata into R.\n\nWhat can differentiate some of these different data files from simple text or Excel files is often the presence of metadata. This additional data can include information about variable types (e.g., specifying a column as numeric, categorical, or date), formatting instructions (e.g., how dates should be displayed), missing value codes, and even labels for categorical levels (indeed, exporting such data from these programs to text data files would lead to removal of the metadata as text files store only data). This valuable metadata is often preserved when importing such data into R but may require you to examine the help documentation of the specific function to understand how it has been incorporated into the imported data.frame (most likely as a data.frame **attribute**).\n\n## Importing common data formats into R\n\nWhile R has built-in functions for basic data import, the `tidyverse` suite of packages offers more efficient and user-friendly tools. For common text-based files like CSV (Comma Separated Values) and TSV (Tab Separated Values), we will use the `readr` package. For Excel files (.xls and .xlsx), the `readxl` package is your go-to. These packages are designed to import clean, tabular data directly into a **tibble**, a modern and enhanced version of R's traditional data.frame.\n\n### Packages\n\n> These should have been installed following previous chapter XX\n\nTo use the functions in these packages, we must load them into our R session.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Load the necessary tidyverse packages\nlibrary(readr)\nlibrary(readxl)\n```\n:::\n\n\n\n\n\n### Our data\n\nIn our working directory, we have a folder called `data/` which contains various data files for use. I exported the data from the `palmerpenguins` R data package into various\nformats for demonstration.\n\n\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n\n```r\n| Root folder\n├── data\n│   ├── penguins.csv\n│   ├── penguins.rds\n│   ├── penguins.tsv\n│   └── penguins.xlsx\n| ...\n```\n\n### Text delimited files\n\nThe package **readr** comes with a number of functions to import different text\ndelimited files. `read_csv()`, `read_tsv()` and `read_delim()` will allow you to\nimport the most common text delimited files. All of the `read_*` functions require the file path to your file provided as a string. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins_csv <- read_csv(\"data/penguins.csv\")\n```\n:::\n\n\n\n\n\nOnce the data is imported, pay close attention to the information printed in your console. This output offers a quick and vital check to confirm that the data was interpreted correctly. It provides key details about the import, including:\n\n- The number of rows and columns in your dataset.\n- The delimiter type that was identified (e.g., a comma, which is standard for CSVs).\n- The data types of each column (e.g., numeric - `dbl`, character - `chr`, date).\n\nThis immediate feedback is incredibly helpful for verifying a successful import and for pinpointing any areas where you might need to adjust the import options to ensure optimal data integrity.\n\nIn the following example, we import `penguins.csv` and see that there are \n\n - 344 rows and 8 columns\n - The delimiter is `,`\n - 3 columns are `chr` and 5 are `dbl`, and their names\n \nIf this was what we expected, then we are ready to work with the data in the \n`penguins_csv` object\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins_csv <- read_csv(\"data/penguins.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 344 Columns: 8\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\nchr (3): species, island, sex\ndbl (5): bill_length_mm, bill_depth_mm, flipper_length_mm, body_mass_g, year\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n\n```{.r .cell-code}\npenguins_csv\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 344 × 8\n   species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g\n   <chr>   <chr>              <dbl>         <dbl>             <dbl>       <dbl>\n 1 Adelie  Torgersen           39.1          18.7               181        3750\n 2 Adelie  Torgersen           39.5          17.4               186        3800\n 3 Adelie  Torgersen           40.3          18                 195        3250\n 4 Adelie  Torgersen           NA            NA                  NA          NA\n 5 Adelie  Torgersen           36.7          19.3               193        3450\n 6 Adelie  Torgersen           39.3          20.6               190        3650\n 7 Adelie  Torgersen           38.9          17.8               181        3625\n 8 Adelie  Torgersen           39.2          19.6               195        4675\n 9 Adelie  Torgersen           34.1          18.1               193        3475\n10 Adelie  Torgersen           42            20.2               190        4250\n# ℹ 334 more rows\n# ℹ 2 more variables: sex <chr>, year <dbl>\n```\n\n\n:::\n:::\n\n\n\n\n\n#### Other examples {.unnumbered}\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Importing a TSV file\npenguins_tsv <- read_tsv(\"data/penguins.tsv\")\n\n# Using the read_delim() function and specifying the delimiter\npenguins_csv <- readr::read_delim(\"data/penguins.csv\", delim = \",\")\npenguins_tsv <- readr::read_delim(\"data/penguins.tsv\", delim = \"\\t\")\n```\n:::\n\n\n\n\n\n### Excel\n\nThe `read_excel()` function from the **readxl** package is used to import Excel\nworksheets from an Excel file. The function requires a file path to your Excel file, \nprovided as a string. Unfortunately, there is no information printed to the console about the import of the file like with the **readr** import functions.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins_xlsx <- read_excel(\"data/penguins.xlsx\")\npenguins_xlsx\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 152 × 8\n   species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g\n   <chr>   <chr>              <dbl>         <dbl>             <dbl>       <dbl>\n 1 Adelie  Torgersen           39.1          18.7               181        3750\n 2 Adelie  Torgersen           39.5          17.4               186        3800\n 3 Adelie  Torgersen           40.3          18                 195        3250\n 4 Adelie  Torgersen           NA            NA                  NA          NA\n 5 Adelie  Torgersen           36.7          19.3               193        3450\n 6 Adelie  Torgersen           39.3          20.6               190        3650\n 7 Adelie  Torgersen           38.9          17.8               181        3625\n 8 Adelie  Torgersen           39.2          19.6               195        4675\n 9 Adelie  Torgersen           34.1          18.1               193        3475\n10 Adelie  Torgersen           42            20.2               190        4250\n# ℹ 142 more rows\n# ℹ 2 more variables: sex <chr>, year <dbl>\n```\n\n\n:::\n:::\n\n\n\n\n\nBy default it will import the the first sheet, but we can specify which sheet to import using the `sheet=` argument. To see what sheet names exist in an excel file we use the `excel_sheets()` function. \n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nreadxl::excel_sheets(\"data/penguins.xlsx\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"Adelie\"    \"Gentoo\"    \"Chinstrap\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Importing a specific sheet from an Excel file\npenguins_adelie_xlsx <- read_excel(\"data/penguins.xlsx\", sheet = \"Adelie\")\npenguins_adelie_xlsx\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 152 × 8\n   species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g\n   <chr>   <chr>              <dbl>         <dbl>             <dbl>       <dbl>\n 1 Adelie  Torgersen           39.1          18.7               181        3750\n 2 Adelie  Torgersen           39.5          17.4               186        3800\n 3 Adelie  Torgersen           40.3          18                 195        3250\n 4 Adelie  Torgersen           NA            NA                  NA          NA\n 5 Adelie  Torgersen           36.7          19.3               193        3450\n 6 Adelie  Torgersen           39.3          20.6               190        3650\n 7 Adelie  Torgersen           38.9          17.8               181        3625\n 8 Adelie  Torgersen           39.2          19.6               195        4675\n 9 Adelie  Torgersen           34.1          18.1               193        3475\n10 Adelie  Torgersen           42            20.2               190        4250\n# ℹ 142 more rows\n# ℹ 2 more variables: sex <chr>, year <dbl>\n```\n\n\n:::\n:::\n\n\n\n\n\n### Fine-tuning data import\n\nImporting clean data into R is relatively simple task, however most data importing functions, including those in `readr` and `readxl`, offer additional options to fine-tune data import given that not all data is the same and data can be quite messy. This includes specifying details such as delimiters, missing value indicators, column types, row skipping and max number of rows to import. It is a good practice to be proactive about data cleaning during data import and this can have many beneficial outcomes. By addressing potential data inconsistencies and structural issues at the source, it will prevent common errors downstream, saving significant time and effort that would otherwise be spent on post-import data remediation.\n\n#### Missing value indicators\n\nR generally expects that an empty cell value means it is missing. However, this can be any value depending on the data source. `readr` and `readxl` import functions use the `na=` argument to specify what values should be considered missing values.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_csv(\"data/penguins.csv\", na = c('', \"N/A\"))\n```\n:::\n\n\n\n\n\n#### Skipping comment lines\n\nThe initial rows of a data file may include comments about the data. These generally start with a hash `#` character. \n`readr` and `readxl` import functions use the `comment=` argument to specify what character is considered the comment character and to skip lines starting with that character. Another argument `skip=` specifies the minimum number of rows to skip before reading any data.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_csv(\"data/penguins.csv\", comment = \"#\")\nread_csv(\"data/penguins.csv\", skip = 2)\n```\n:::\n\n\n\n\n\n#### Importing a maximum number of rows\n\nWith very large datasets, it may be wise to initially import only a few rows to inspect the data. `readr` and `readxl` import functions use the argument `n_max=` to specify the maximum number of data rows to read.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_csv(\"data/penguins.csv\", n_max = 10)\n```\n:::\n\n\n\n\n\n## R data files\n\nFor R data files, specifically `.rds` files, we continue to use the `readr` package and the function `read_rds()`. No import information is provided when importing an `.rds` file\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins_rds <- readr::read_rds('data/penguins.rds')\n```\n:::\n\n\n\n\n\nFor `.Rdata` and `.rda` files, we use the R function `load()`. These files have saved R objects including their name so there is no assigning of the result and we must observe what objects were loaded into the current R session.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nload('data/example.Rdata')\n```\n:::\n\n\n\n\n\n\n## Other data types\n\nBeyond these common formats, R boasts a rich ecosystem of packages for importing virtually any data type. This includes packages to read data from other statistical software (like SPSS, Stata, and SAS), directly from Google Sheets, or by connecting to various types of databases. While we won't delve into these here, be aware that R's integration capabilities extend far and wide within the IT landscape, allowing it to seamlessly handle diverse data sources and types.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(haven)\nsas_data <- haven::read_sas(\"sasdata\")\nsas_data <- haven::read_spss(\"spss\")\nlibrary(googlesheets4)\ngooglesheets4::read_sheet(\"url\")\nlibrary(DBI)\nlibrary(odbc)\nDBI::dbConnect(odbc::odbc(), host='..', )\n```\n:::\n\n\n\n\n\n## Exploring Your Imported Data\n\n```\nFunctions for inspecting data frames: head(), tail(), str(), summary(), dim(), colnames().\nAccessing variables (columns) using \\$ notation.\n```\n\nUnderstanding the structure and properties of your imported data will inform your subsequent analysis. We will cover both base R functions and tidyverse approaches, highlighting the differences in output, particularly between data.frame and tibble objects\n\n### What's the Difference: data.frame vs. tibble?\n\nAs you've learned, `readr` and `readxl` typically import data as a tibble. A tibble is a modern reimagining of the data.frame, designed to be more user-friendly and consistent. While both store tabular data, there are key differences in how they behave and how they are displayed, especially during exploration.\n\nWe imported the `penguins_csv` as a **tibble** and print it to the console to check it contents. Doing this again but now explaining what we see\n\n- `# A tibble: 344 × 8` we have a tibble with 344 rows and 8 columns\n- `species`, `island`, `...` are the column names\n- `<chr>` and `<dbl>` under the column names describe each column data type - character and (numeric) double\n- The first 10 rows of the data\n- `# ℹ 334 more rows` that there are more rows not sown.\n\nThus a tibble provides a concise summary of the data highlighting all the things we should check about our data once it has been imported.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins_csv\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 344 × 8\n   species island    bill_length_mm bill_depth_mm flipper_length_mm body_mass_g\n   <chr>   <chr>              <dbl>         <dbl>             <dbl>       <dbl>\n 1 Adelie  Torgersen           39.1          18.7               181        3750\n 2 Adelie  Torgersen           39.5          17.4               186        3800\n 3 Adelie  Torgersen           40.3          18                 195        3250\n 4 Adelie  Torgersen           NA            NA                  NA          NA\n 5 Adelie  Torgersen           36.7          19.3               193        3450\n 6 Adelie  Torgersen           39.3          20.6               190        3650\n 7 Adelie  Torgersen           38.9          17.8               181        3625\n 8 Adelie  Torgersen           39.2          19.6               195        4675\n 9 Adelie  Torgersen           34.1          18.1               193        3475\n10 Adelie  Torgersen           42            20.2               190        4250\n# ℹ 334 more rows\n# ℹ 2 more variables: sex <chr>, year <dbl>\n```\n\n\n:::\n:::\n\n\n\n\n\nIt is possible that you may have in hand a regular data.frame. If you were to print this\nto the console, you would see much less informative information and many more rows of data.\nIn the following example I limited the data.frame printing to 10 rows, but it would otherwise print the first 1000 rows by default, flooding your screen.\n\nNote that we can see the column names and their values, but that the data.frame dimensions and column data types are not explicitly shown.\n\n\n\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins_csv_df <- as.data.frame(penguins_csv)\npenguins_csv_df\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   species    island bill_length_mm bill_depth_mm flipper_length_mm body_mass_g\n1   Adelie Torgersen           39.1          18.7               181        3750\n2   Adelie Torgersen           39.5          17.4               186        3800\n3   Adelie Torgersen           40.3          18.0               195        3250\n4   Adelie Torgersen             NA            NA                NA          NA\n5   Adelie Torgersen           36.7          19.3               193        3450\n6   Adelie Torgersen           39.3          20.6               190        3650\n7   Adelie Torgersen           38.9          17.8               181        3625\n8   Adelie Torgersen           39.2          19.6               195        4675\n9   Adelie Torgersen           34.1          18.1               193        3475\n10  Adelie Torgersen           42.0          20.2               190        4250\n11  Adelie Torgersen           37.8          17.1               186        3300\n12  Adelie Torgersen           37.8          17.3               180        3700\n      sex year\n1    male 2007\n2  female 2007\n3  female 2007\n4    <NA> 2007\n5  female 2007\n6    male 2007\n7  female 2007\n8    male 2007\n9    <NA> 2007\n10   <NA> 2007\n11   <NA> 2007\n12   <NA> 2007\n [ reached 'max' / getOption(\"max.print\") -- omitted 332 rows ]\n```\n\n\n:::\n:::\n\n\n\n\n\nWe would use these functions to query our data.frame properties.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(penguins_csv_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t344 obs. of  8 variables:\n $ species          : chr  \"Adelie\" \"Adelie\" \"Adelie\" \"Adelie\" ...\n $ island           : chr  \"Torgersen\" \"Torgersen\" \"Torgersen\" \"Torgersen\" ...\n $ bill_length_mm   : num  39.1 39.5 40.3 NA 36.7 39.3 38.9 39.2 34.1 42 ...\n $ bill_depth_mm    : num  18.7 17.4 18 NA 19.3 20.6 17.8 19.6 18.1 20.2 ...\n $ flipper_length_mm: num  181 186 195 NA 193 190 181 195 193 190 ...\n $ body_mass_g      : num  3750 3800 3250 NA 3450 ...\n $ sex              : chr  \"male\" \"female\" \"female\" NA ...\n $ year             : num  2007 2007 2007 2007 2007 ...\n```\n\n\n:::\n\n```{.r .cell-code}\nhead(penguins_csv_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  species    island bill_length_mm bill_depth_mm flipper_length_mm body_mass_g\n1  Adelie Torgersen           39.1          18.7               181        3750\n2  Adelie Torgersen           39.5          17.4               186        3800\n3  Adelie Torgersen           40.3          18.0               195        3250\n4  Adelie Torgersen             NA            NA                NA          NA\n5  Adelie Torgersen           36.7          19.3               193        3450\n6  Adelie Torgersen           39.3          20.6               190        3650\n     sex year\n1   male 2007\n2 female 2007\n3 female 2007\n4   <NA> 2007\n5 female 2007\n6   male 2007\n```\n\n\n:::\n\n```{.r .cell-code}\ndim(penguins_csv_df)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 344   8\n```\n\n\n:::\n\n```{.r .cell-code}\nnames(penguins_csv)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"species\"           \"island\"            \"bill_length_mm\"   \n[4] \"bill_depth_mm\"     \"flipper_length_mm\" \"body_mass_g\"      \n[7] \"sex\"               \"year\"             \n```\n\n\n:::\n:::\n",
    "supporting": [
      "chapter_5_external_data_and_data_import_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}