project:
  type: book

book:
  title: "Introduction to R for data analysis in scientific research"
  author: "Shaun Nielsen and AI"
  date: "29/05/2025"
  chapters:
    - index.qmd
    - chapter_0_introduction.qmd
    - chapter_1_why_r_and_what_is_rstudio.qmd
    - chapter_2_initial_steps.qmd
    - chapter_3_a_gentle_first_analysis.qmd
    - chapter_4_using_a_dataframe_for_your_first_analysis.qmd
    - chapter_5_data_import.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: darkly
    cover-image: cover.png
    css: styles.css

editor: visual

execute:
  freeze: auto
