{
  "hash": "c9a9adf50d89a10bfe8de1a4e1bedf72",
  "result": {
    "engine": "knitr",
    "markdown": "# A gentle introduction to R\n\nThis chapter provides a concrete example of R's usefulness by guiding you through \na simple data analysis scenario. You will create two R scripts, exploring distinct \nmethods for handling data: first with individual vectors, then with the more robust \ndata.frame structure. In each case, you'll have a concise, reproducible workflow\ncovering data input, visualization, statistical summaries, and a statistical test,\nproviding all the essential steps for others to replicate your work.\n\n## The scenario\n\nYou have collected the counts of insects on different individual plants under two \nexperimental treatments - one with an insecticide and another as a  control treatment \nwithout the insecticide.\n\nControl treatment: 8, 9, 10, 9, 9, 12, 12, 12, 13, 10 \n\nInsecticide treatment: 2, 5, 2, 0, 2, 3, 4, 4, 2\n\nLet's enter these data into R and see how we can easily analyse the data.\n\n## Script 1 - using data vectors\n\nCreate a new R script and copy the code below to the script as you work through\nthe section. Include comments where necessary.\n\n### Simple data entry\n\nWe use the `c()` function to create simple vectors. Keep in mind that this method\nis suitable for quick data entry, and not the typical method for entering data into\nR.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntreat_ctrl = c(8, 9, 10, 9, 9, 12, 12, 12, 13, 10)\ntreat_insect = c(2, 5, 2, 0, 2, 3, 4, 4, 2)\n```\n:::\n\n\n\n\n\nWe can verify that the data has been entered correctly into R by either 1) printing \nthe values to the console, or 2) examining the \"Environment\" panel in RStudio \n(located in the top-right).\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntreat_ctrl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  8  9 10  9  9 12 12 12 13 10\n```\n\n\n:::\n\n```{.r .cell-code}\ntreat_insect\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2 5 2 0 2 3 4 4 2\n```\n\n\n:::\n:::\n\n\n\n\n\nImage of RStudio environment\n\n\n\n\n{{< placeholder >}}\n\n\n\n\n\n\n\n\n### Data visalisation\n\nWe can use one of R's various plotting functions to visualize and better understand the \npatterns within the data. For example, the `boxplot()` function create boxplots. In \nthis case, we pass the two vectors, one after the other to `boxplot()`. While \nthis would create a basic plot, we want to add informative axis labels. To label \neach boxplot along the x-axis, we use the `names=` argument and provide a vector containing \ntwo text values. To label the x-axis and y-axis, we use the `ylab=` and `xlab=` arguments, \nrespectively, with single text values of the axis titles. Note the use of quotation \nmarks (`\"`) for these text values.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(treat_ctrl, treat_insect,\n        names = c('Control', 'Insecticide'),\n        xlab = \"Treatment\",\n        ylab = 'Insect counts')\n```\n\n::: {.cell-output-display}\n![](chapter_2_a_gentle_introduction_to_r_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n\n\n### Statistical summaries\n\nWe can obtain simple statistical summaries with such functions as `mean()`, `median()`,\n`sd()`, `range()`. As you might notice, this involves a fair amount of typing. \nWe will learn more efficient methods for obtaining these summaries later.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(treat_ctrl)\nmean(treat_insect)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10.4\n[1] 2.666667\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(treat_ctrl)\nsd(treat_insect)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.712698\n[1] 1.5\n```\n\n\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlength(treat_ctrl)\nlength(treat_insect)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10\n[1] 9\n```\n\n\n:::\n:::\n\n\n\n\n\n### A statistical test\n\nWe can use a `t.test()` to statistically compare the means of values from the\ntwo treatment groups. We pass the two vectors, one after the other, to the `t.test()`\nfunction to conduct a t-test. We include the argument `var.equal = TRUE` for a \ntraditional t.test. \n\nThe output of `t.test()` provides various information about the statistics involved\nin a t-test. The t statistic, degrees of freedom and p value are present. The p-value \n(4.177e-08) is less than 0.05, leading us to conclude that there is a statistically \nsignificant difference between the means of the two treatment groups. The mean\nof the control group (mean of x, 10.4) is greater than the mean of the insecticide \ntreatment (mean of y, 2.67).\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(treat_ctrl, treat_insect, var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  treat_ctrl and treat_insect\nt = 10.415, df = 17, p-value = 8.508e-09\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n 6.166701 9.299966\nsample estimates:\nmean of x mean of y \n10.400000  2.666667 \n```\n\n\n:::\n:::\n\n\n\n\n\n### What your script should look like\n\nHaving worked through the section and copying the code across to your own computer,\nyour script should resemble the code below. If all is good, save script to your computer.\nWell done! You just created your first analysis script.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Data input\ntreat_ctrl = c(8, 9, 10, 9, 9, 12, 12, 12, 13, 10)\ntreat_insect = c(2, 5, 2, 0, 2, 3, 4, 4, 2)\n\n# Data check\ntreat_ctrl\ntreat_insect\n\n# Data visualisation\nboxplot(treat_ctrl, treat_insect,\n        names = c('Control', 'Insecticide'),\n        ylab = 'Insect counts')\n\n# Data summaries\nmean(treat_ctrl)\nmean(treat_insect)\n\nsd(treat_ctrl)\nsd(treat_insect)\n\nlength(treat_ctrl)\nlength(treat_insect)\n\n# Comparison of means between treaments using t-test\nt.test(treat_ctrl, treat_insect var.equal = TRUE)\n```\n:::\n\n\n\n\n\n\n## Script 2 - Using a data.frame\n\nCreate a new R script and copy the code below to the script as you work through\nthe section. Include comments where necessary.\n\n### Using a data.frame to store data\n\nWe typically organize our data in a data structure called a **data.frame**. This is\na rectangular table-like structure containing columns of data, where the rows are\nobservations of related elements across the columns. \n\nWe will create a data.frame of our data by entering the data manually, noting that\nwe are doing it here for demonstration purposes. In practice, you would \ntypically use other methods to create data tables, such as creating it in \nExcel or obtaining it from other sources, and then importing it into R as a data.frame.\n\nNote that breaking code into different lines can improve its readability.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsect_count_data <-\n  data.frame(\n    Treatment = c('ctrl','ctrl','ctrl','ctrl','ctrl',\n                  'ctrl','ctrl','ctrl','ctrl','ctrl',\n                  'insect','insect','insect','insect','insect',\n                  'insect','insect','insect','insect'),\n    Count = c(8, 9, 10, 9, 9, 12, 12, 12, 13, 10, \n              2, 5, 2, 0, 2, 3, 4, 4, 2)\n  )\n```\n:::\n\n\n\n\n\nNow we have a data.frame holding the data together in an object called `insect_count_data`.\nPrinting it to the console show the column and row nature of a data.frame.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsect_count_data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Treatment Count\n1       ctrl     8\n2       ctrl     9\n3       ctrl    10\n4       ctrl     9\n5       ctrl     9\n6       ctrl    12\n7       ctrl    12\n8       ctrl    12\n9       ctrl    13\n10      ctrl    10\n11    insect     2\n12    insect     5\n13    insect     2\n14    insect     0\n15    insect     2\n16    insect     3\n17    insect     4\n18    insect     4\n19    insect     2\n```\n\n\n:::\n:::\n\n\n\n\n\nUsing the `str()` function displays the structure of the data.frame. This data.frame \ncontains 19 observations and 2 variables (columns). The column names are `Treatment` \nand `Count`. After the colum names we see `chr` and `num`, and these tell use the\n**data types** of the columns. R uses data types to understand what kind of information\nexisits in each column.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstr(insect_count_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n'data.frame':\t19 obs. of  2 variables:\n $ Treatment: chr  \"ctrl\" \"ctrl\" \"ctrl\" \"ctrl\" ...\n $ Count    : num  8 9 10 9 9 12 12 12 13 10 ...\n```\n\n\n:::\n:::\n\n\n\n\n\nWe can access the data within specific columns using the `$` symbol. This returns\nthe values as vectors analogous to the vectors we create earlier in this chapter (X.X).\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninsect_count_data$Treatment\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"ctrl\"   \"ctrl\"   \"ctrl\"   \"ctrl\"   \"ctrl\"   \"ctrl\"   \"ctrl\"   \"ctrl\"  \n [9] \"ctrl\"   \"ctrl\"   \"insect\" \"insect\" \"insect\" \"insect\" \"insect\" \"insect\"\n[17] \"insect\" \"insect\" \"insect\"\n```\n\n\n:::\n\n```{.r .cell-code}\ninsect_count_data$Count\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  8  9 10  9  9 12 12 12 13 10  2  5  2  0  2  3  4  4  2\n```\n\n\n:::\n:::\n\n\n\n\n\n### Data visalisation\n\nWe will create a boxplot again using the `boxplot()` function, but time using\ndata.frame columns and a special R notation called a **formula**.\n\nA formula, such as `y ~ group`, is used where `y` represents a numeric vector of data \nvalues, and `group` a grouping variable used to split the data. The **first** \nargument of `boxplot()` is the formula.\n\nWhen passing data in this formulaic way, the boxplot labels are automatically \npopulated, meaning we do not need to use the `names=` argument. Notice\nthat the x- and y-axis labels are derived from the code used in the formula.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(insect_count_data$Count ~ insect_count_data$Treatment)\n```\n\n::: {.cell-output-display}\n![](chapter_2_a_gentle_introduction_to_r_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n\n\n\n\nMany R functions are designed to work with data.frames and include a `data=` argument\nto specify an input data.frame to use. In this approach, we provide the data.frame\nnames to the `data=` argument and then refer to the columns directly by their names \nwithin the formula (not using the `$`). Notice that the default x- and y-axis titles \nare often more informative when using the formula and data argument. However, you can still \ncustomize them using the `xlab=` and `ylab=` arguments if desired. While we are\nhere, lets change the colour using `col=`.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(Count ~ Treatment, data = insect_count_data,\n        col = 'lightblue')\n```\n\n::: {.cell-output-display}\n![](chapter_2_a_gentle_introduction_to_r_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\n\n\n\n### A statistical summaries\n\nThere are also functions that are helpful for summarizing data within a data.frame. \nThe `aggregate()` function takes a formula as its first argument to describe a response\nand grouping structure, followed by the `data=` argument to specify the data.frame, \nand a `FUN=` argument to indicate the statistical function to apply. Note that the statistical\nfunction is provided without parentheses within the `FUN=` argument (e.g., `FUN=mean`,\nnot `FUN=mean()`).\n\nAgain, you might notice that this involves a fair amount repeated typing. The output\nis more concise than the that from earlier in the chapter (X.X)\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\naggregate(Count ~ Treatment, data = insect_count_data, FUN = mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Treatment     Count\n1      ctrl 10.400000\n2    insect  2.666667\n```\n\n\n:::\n\n```{.r .cell-code}\naggregate(Count ~ Treatment, data = insect_count_data, FUN = sd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Treatment    Count\n1      ctrl 1.712698\n2    insect 1.500000\n```\n\n\n:::\n\n```{.r .cell-code}\naggregate(Count ~ Treatment, data = insect_count_data, FUN = length)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  Treatment Count\n1      ctrl    10\n2    insect     9\n```\n\n\n:::\n:::\n\n\n\n\n\n### Statistical test\n\nThe `t.test()` function is also designed to work with data.frames. Following the \nfunction structures above, here's how you would apply it.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(Count ~ Treatment, data = insect_count_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tWelch Two Sample t-test\n\ndata:  Count by Treatment\nt = 10.491, df = 16.993, p-value = 7.664e-09\nalternative hypothesis: true difference in means between group ctrl and group insect is not equal to 0\n95 percent confidence interval:\n 6.178112 9.288555\nsample estimates:\n  mean in group ctrl mean in group insect \n           10.400000             2.666667 \n```\n\n\n:::\n:::\n\n\n\n\n\n### What your script should look like\n\nHaving worked through the section and copying the code across to your own computer,\nyour script should resemble the code below. I have only included the code that would\ngo into the final analysis script, and removed some of the demonstration code.\nSave script to your computer. Well done! You just conducted an analysis using the\nmost import data structure in R - the data.frame.\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Data input\ninsect_count_data <-\n  data.frame(\n    Treatment = c('ctrl','ctrl','ctrl','ctrl','ctrl',\n                  'ctrl','ctrl','ctrl','ctrl','ctrl',\n                  'insect','insect','insect','insect','insect',\n                  'insect','insect','insect','insect'),\n    Count = c(8, 9, 10, 9, 9, 12, 12, 12, 13, 10, \n              2, 5, 2, 0, 2, 3, 4, 4, 2)\n  )\n\n# Data check\ninsect_count_data\n\n# There are 19 rows of data\n# Treatment is character type\n# Count is numeric type\nstr(insect_count_data)\n\n\n# Data visualisation\nboxplot(Count ~ Treatment, data = insect_count_data,\n        col = 'lightblue')\n\n# Data summaries\naggregate(Count ~ Treatment, data = insect_count_data, FUN = mean)\naggregate(Count ~ Treatment, data = insect_count_data, FUN = sd)\naggregate(Count ~ Treatment, data = insect_count_data, FUN = length)\n\n# Statistical test\nt.test(Count ~ Treatment, data = insect_count_data)\n```\n:::\n\n\n\n\n\n## Summary\n\nThis introductory chapter provided a hands-on experience with R for basic data analysis, \ndemonstrating how to transform raw data into reproducible insights. You learned two \nfundamental ways to handle data in R: using vectors for simple, quick entry and,\nmore importantly, organizing data into data.frames — R's preferred tabular data structure. \nThrough a practical example of insect counts under different treatments, you explored \nkey steps in a data analysis workflow: data input, data visualization using boxplots, \ncalculating basic statistical summaries like the mean, standard deviation, and number of\nvalues (length), and performing a statistical test (t-test) to compare group means.\nYou also gained familiarity with R's formula notation for efficient data manipulation \nand visualization within data.frames. This foundational understanding of R scripts \nand data structures prepares you for more advanced analyses, particularly for \nimporting data from external files, which will be covered in the next chapter.\n\n",
    "supporting": [
      "chapter_2_a_gentle_introduction_to_r_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}