{
  "hash": "96752d7e462d322fb728dd48de7cf25c",
  "result": {
    "engine": "knitr",
    "markdown": "# A gentle first analysis\n\nThis chapter provides a concrete example of R's usefulness by guiding you through a simple data analysis scenario. You will create an R script, enter data and use R to explore the data, visualise it, create statistical summaries and conduct a statistical test. By the end you will have a concise, reproducible workflow covering all the essential steps you used and a document for others to replicate your work.\n\n## The scenario\n\nYou have collected the counts of insects on different individual plants under two experimental treatments - one with an insecticide and another as a control treatment without the insecticide.\n\nControl treatment: 8, 9, 10, 9, 9, 12, 12, 12, 13, 10\n\nInsecticide treatment: 2, 5, 2, 0, 2, 3, 4, 4, 2\n\nLet's enter these data into R and see how we can easily analyse the data.\n\n> Create a new R script and copy the code below to the script as you work through the section. Include comments where necessary.\n\n## Simple data entry\n\nWe use the `c()` function to create simple **vectors**. Think of these of sets of related values. Keep in mind that this method is suitable for quick data entry, and not the typical method for entering data into R.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntreat_ctrl = c(8, 9, 10, 9, 9, 12, 12, 12, 13, 10)\ntreat_insect = c(2, 5, 2, 0, 2, 3, 4, 4, 2)\n```\n:::\n\n\nWe can verify that the data has been entered correctly into R by either 1) printing the values to the console, or 2) examining the \"Environment\" panel in RStudio (located in the top-right).\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntreat_ctrl\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  8  9 10  9  9 12 12 12 13 10\n```\n\n\n:::\n\n```{.r .cell-code}\ntreat_insect\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 2 5 2 0 2 3 4 4 2\n```\n\n\n:::\n:::\n\n\nImage of RStudio environment {{< placeholder >}}\n\n### Data visalisation\n\nWe can use one of R's various plotting functions to visualize and better understand the patterns within the data. For example, the `boxplot()` function create boxplots. In this case, we pass the two vectors, one after the other to `boxplot()`. While this would create a basic plot, we want to add informative axis labels. To label each boxplot along the x-axis, we use the `names=` argument and provide a vector containing two text values. To label the x-axis and y-axis, we use the `ylab=` and `xlab=` arguments, respectively, with single text values of the axis titles. Note the use of quotation marks (`\"`) for these text values.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(treat_ctrl, treat_insect,\n        names = c('Control', 'Insecticide'),\n        xlab = \"Treatment\",\n        ylab = 'Insect counts')\n```\n\n::: {.cell-output-display}\n![](chapter_3_a_gentle_first_analysis_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n### Statistical summaries\n\nWe can obtain simple statistical summaries with such functions as `mean()`, `median()`, `sd()`, `range()`. As you might notice, this involves a fair amount of typing. We will learn more efficient methods for obtaining these summaries later.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(treat_ctrl)\nmean(treat_insect)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10.4\n[1] 2.666667\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(treat_ctrl)\nsd(treat_insect)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1.712698\n[1] 1.5\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlength(treat_ctrl)\nlength(treat_insect)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10\n[1] 9\n```\n\n\n:::\n:::\n\n\n### A statistical test\n\nWe can use a `t.test()` to statistically compare the means of values from the two treatment groups. We pass the two vectors, one after the other, to the `t.test()` function to conduct a t-test. We include the argument `var.equal = TRUE` for a traditional t.test.\n\nThe output of `t.test()` provides various information about the statistics involved in a t-test. The t statistic, degrees of freedom and p value are present. The p-value (4.177e-08) is less than 0.05, leading us to conclude that there is a statistically significant difference between the means of the two treatment groups. The mean of the control group (mean of x, 10.4) is greater than the mean of the insecticide treatment (mean of y, 2.67).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(treat_ctrl, treat_insect, var.equal = TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tTwo Sample t-test\n\ndata:  treat_ctrl and treat_insect\nt = 10.415, df = 17, p-value = 8.508e-09\nalternative hypothesis: true difference in means is not equal to 0\n95 percent confidence interval:\n 6.166701 9.299966\nsample estimates:\nmean of x mean of y \n10.400000  2.666667 \n```\n\n\n:::\n:::\n\n\n### What your script should look like\n\nHaving worked through the section and copying the code across to your own computer, your script should resemble the code below. If all is good, save script to your computer. Well done! You just created your first analysis script.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Data input\ntreat_ctrl = c(8, 9, 10, 9, 9, 12, 12, 12, 13, 10)\ntreat_insect = c(2, 5, 2, 0, 2, 3, 4, 4, 2)\n\n# Data check\ntreat_ctrl\ntreat_insect\n\n# Data visualisation\nboxplot(treat_ctrl, treat_insect,\n        names = c('Control', 'Insecticide'),\n        ylab = 'Insect counts')\n\n# Data summaries\nmean(treat_ctrl)\nmean(treat_insect)\n\nsd(treat_ctrl)\nsd(treat_insect)\n\nlength(treat_ctrl)\nlength(treat_insect)\n\n# Comparison of means between treaments using t-test\nt.test(treat_ctrl, treat_insect var.equal = TRUE)\n```\n:::\n\n\n## Summary\n\nThis chapter provided a hands-on experience with R for basic data analysis, demonstrating input raw data and \\[generate insights\\]. You learned a fundamental way to handle data in R: using vectors for simple, quick entry. Through a practical example of insect counts under different treatments, you explored key steps in a data analysis workflow: data input, data visualization using boxplots, calculating basic statistical summaries like the mean, standard deviation, and number of values (length), and performing a statistical test (t-test) to compare group means. You recorded all the steps in an R script - a recipe for the analysis workfllow - and which in a fundamental unit of reproducible analysis. In the next chapter, we will conduct the same analysis but using R preferred tabular data structure - the data.frame.\n",
    "supporting": [
      "chapter_3_a_gentle_first_analysis_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}